In [1]:
import nltk
import string
import contractions
import pandas as pd
from textblob import TextBlob
from nltk.tokenize import sent_tokenize
from nltk.stem import PorterStemmer, SnowballStemmer, WordNetLemmatizer
from nltk.corpus import stopwords 
from sklearn.feature_extraction.text import TfidfVectorizer


df = pd.read_csv('nlp_sample_dataset.csv')

In [2]:
df.head()

   id                                               text     label
0   1  I absolutely loved this movie! The acting was ...  positive
1   2  The film was too long and boring. I almost fel...  negative
2   3  Great visuals, but the plot didn’t make much s...   neutral
3   4  An outstanding performance by the lead actor. ...  positive
4   5  Terrible experience. The screenplay was weak a...  negative

In [3]:
df['lowercase'] = df['text'].str.lower()
df.head()

,id,text,label,lowercase
0,1,I absolutely loved this movie! The acting was ...,positive,i absolutely loved this movie! the acting was ...
1,2,The film was too long and boring. I almost fel...,negative,the film was too long and boring. i almost fel...
2,3,"Great visuals, but the plot didn’t make much s...",neutral,"great visuals, but the plot didn’t make much s..."
3,4,An outstanding performance by the lead actor. ...,positive,an outstanding performance by the lead actor. ...
4,5,Terrible experience. The screenplay was weak a...,negative,terrible experience. the screenplay was weak a...

In [4]:
df['punctuation'] = df['lowercase'].apply(lambda x: ''.join([c for c in x if c not in string.punctuation]))
df.head()

,id,text,label,lowercase,punctuation
0,1,I absolutely loved this movie! The acting was ...,positive,i absolutely loved this movie! the acting was ...,i absolutely loved this movie the acting was b...
1,2,The film was too long and boring. I almost fel...,negative,the film was too long and boring. i almost fel...,the film was too long and boring i almost fell...
2,3,"Great visuals, but the plot didn’t make much s...",neutral,"great visuals, but the plot didn’t make much s...",great visuals but the plot didn’t make much se...
3,4,An outstanding performance by the lead actor. ...,positive,an outstanding performance by the lead actor. ...,an outstanding performance by the lead actor t...
4,5,Terrible experience. The screenplay was weak a...,negative,terrible experience. the screenplay was weak a...,terrible experience the screenplay was weak an...

In [5]:
df['mispelling'] = df.apply(lambda x: str(TextBlob(x['punctuation']).correct()))
df.head()

KeyError: 'punctuation'

In [ ]:
df['contractions'] = df['mispelling'].apply(contractions.fix)
df.head()

KeyError: 'mispelling'

In [ ]:
df['stopwords'] = df['contractions'].apply(lambda x: [w for w in x if w not in stopwords.words('english')])
df.head()

In [ ]:
ps = PorterStemmer()
sbs = SnowballStemmer()
wnl = WordNetLemmatizer()

for w in df['lowercase'][0]:
    print(ps.stem(w), sbs.stem(w), wnl.lemmatize(w))

In [ ]:
import spacy 

nlp = spacy.load('en_core_web_sm')

doc = nlp(df['lowercase'][0])

for token in doc:
    print(token.text, token.pos_, token.lemma_, token.ent_type_)

In [ ]:
sentence = [w for w in df['lowercase'][0]]
tf_idf = TfidfVectorizer()
tf_idf_fit = tf_idf.fit_transform([sentence])

from sklearn.metrics.pairwise import cosine_similarity

print(cosine_similarity(tf_idf_fit[0], tf_idf_fit[1]))

In [ ]:
from gensim.models import Word2Vec
target = 'hello'

cbow = Word2Vec(sentences= df['lowercase'], vector_size =50, window=5, min_count=1, sg=0)
skip = Word2Vec(sentences= df['lowercase'], vector_size =50, window=5, min_count=1, sg=1)